// #include <com/sun/star/beans/XPropertySet.idl>
#include <com/sun/star/table/XCellRange.idl>
#include <com/sun/star/uno/XInterface.idl>

module org { module openoffice { module sheet { module addin {
    interface XLox365 : com::sun::star::uno::XInterface {
        sequence< sequence< any > > DBG_ECHO(
            [in] sequence< sequence< any > > x1
        );
        sequence< sequence< any > > DBG_ECHO2(
            [in] sequence< any > x1
        );
        sequence< sequence< any > > DBG_ECHO3(
            [in] any x1
        );
        sequence< sequence< any > > DBG_PY(
            [in] com::sun::star::table::XCellRange cr,
            [in] string evalx
        );
        sequence< sequence< any > > FILTER(
            [in] sequence< sequence< any > > array,
            [in] sequence< sequence< any > > include,
            [in] any ifEmpty
        );
        sequence< sequence< any > > SORT(
            [in] sequence< sequence< any > > array,
            [in] any sortIndex,
            [in] any sortOrder
        );
        sequence< sequence< any > > TEXTSPLIT(
            [in] string text,
            [in] string colDelimiter
        );
        sequence< sequence< any > > TOCOL(
            [in] sequence< sequence< any > > array
        );
        sequence< sequence< any > > UNIQUE(
            [in] sequence< sequence< any > > array
        );
        sequence< sequence< any > > XLOOKUP(
            [in] any lookupValue,
            [in] com::sun::star::table::XCellRange lookupArray,
            [in] com::sun::star::table::XCellRange returnArray,
            [in] any ifNotFound
        );
    };
}; }; }; };
